import { inMemoryStore } from './store';
import { DocumentItem } from './types';

export async function getDocuments(
  workspaceId: string,
  filter?: { projectId?: string; category?: string; isCompanyBrain?: boolean }
): Promise<DocumentItem[]> {
  return Array.from(inMemoryStore.documents.values())
    .filter((doc) => {
      if (doc.workspaceId !== workspaceId) return false;
      if (filter?.projectId && doc.projectId !== filter.projectId) return false;
      if (filter?.category && doc.category !== filter.category) return false;
      if (filter?.isCompanyBrain !== undefined && Boolean(doc.isCompanyBrainResource) !== filter.isCompanyBrain) return false;
      return true;
    })
    .sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
}

export async function getDocumentById(id: string): Promise<DocumentItem | null> {
  return inMemoryStore.documents.get(id) || null;
}

export async function createDocument(workspaceId: string, data: Partial<DocumentItem>): Promise<DocumentItem> {
  const id = `doc_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
  const doc: DocumentItem = {
    id,
    workspaceId,
    projectId: data.projectId,
    title: data.title || 'Untitled Document',
    content: data.content || '',
    category: data.category || 'general',
    tags: data.tags || [],
    authorId: data.authorId || 'usr_owner_demo',
    authorName: data.authorName || 'Cursis Team',
    version: 1,
    isCompanyBrainResource: data.isCompanyBrainResource ?? true,
    summary: data.summary || (data.content ? `${data.content.substring(0, 100)}...` : ''),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  inMemoryStore.documents.set(id, doc);
  return doc;
}

export async function updateDocument(id: string, updates: Partial<DocumentItem>): Promise<DocumentItem | null> {
  const doc = inMemoryStore.documents.get(id);
  if (!doc) return null;

  const updated: DocumentItem = {
    ...doc,
    ...updates,
    version: doc.version + 1,
    updatedAt: new Date().toISOString(),
  };

  inMemoryStore.documents.set(id, updated);
  return updated;
}

// Generate document on the spot (e.g. Kickoff spec, proposal deck, technical SOW)
export async function generateDocumentFromPrompt(
  workspaceId: string,
  prompt: string,
  category: DocumentItem['category'] = 'kickoff',
  projectId?: string
): Promise<DocumentItem> {
  const ws = inMemoryStore.workspaces.get(workspaceId);
  const tone = ws?.settings.companyTone || 'Direct, authoritative, and structured';

  const title = prompt.length > 40 ? `${prompt.substring(0, 37)}...` : prompt;
  const content = `# ${title}\n\n*Generated by Ordis AI Engine*\n\n## 1. Executive Overview\nThis document outlines the strategic specifications, timeline milestones, and delivery parameters formulated for ${prompt}.\n\n## 2. Technical Architecture & Scope\n- Frontend: Next.js App Router, Tailwind CSS, high-fidelity micro-interactions.\n- Backend: Firebase Auth & Session Middleware, Server Actions, REST endpoints.\n- AI Integration: Ordis Autonomous Agent layer with proactive anomaly detection.\n\n## 3. Delivery Milestones\n- Phase 1: Architecture Alignment & Core Modules\n- Phase 2: Autonomous Agent Pipeline Integration\n- Phase 3: Validation, Security Audit, and Handover\n\n## 4. Governance & Company Standards\nApplied Workspace Tone: ${tone}`;

  return createDocument(workspaceId, {
    title: `Spec: ${title}`,
    content,
    category,
    projectId,
    isCompanyBrainResource: true,
    tags: ['Ordis-Generated', category],
  });
}
